permission: "orbital.use"

disabled-worlds:
  - ""

cooldowns:
  enabled: false
  nuke: 300
  stab: 120
  dogs: 180
  chunkeater: 600
  stasis: 240

rod:
  distance: 100
  throw-rod: true

nuke:
  rings: 10
  height: 15
  yield: 6.0
  tnt-per-ring-base: 40
  tnt-per-ring-increase: 2
  fuse-ticks: 160
  center-tnt: true
  Animated-rings: true
  damaged-rings: true

stab:
  yield: 4.0

dogs:
  count: 50
  radius: 5.0
  effect-duration: 2400
  effects:
    - "SPEED:1"
    - "STRENGTH:2"